export const ENDPOINTS = {
  GET_ACCOUNT: "/account",
  GET_VERSION_STEMS: "/version-stems",
  GET_APPLICATION_TRACKS: "/application-tracks",
  HANDLE_DISCORD_INTERACTION: "/discord/interaction",
  GET_SETTINGS: "/settings",
  GET_SESSIONS: "/sessions",
  GET_SESSION: "/sessions",
  GET_SESSION_VERSIONS: "/sessions/versions",
  GET_SESSION_VERSION: "/sessions/versions",
  GET_ADDRESSES_INFO: "/address",
  GET_ADDRESS_INFO: "/address",
  GET_PRIVATE_ADDRESS_DATA: "/private",
  AUTH: "/auth",
};
