// TODO: update endpoints to remove the duplicated endpoints
export const ENDPOINTS = {
  GET_ACCOUNT: "/account",
  GET_VERSION_STEMS: "/version-stems",
  GET_APPLICATION_TRACKS: "/application-tracks",
  HANDLE_DISCORD_INTERACTION: "/discord/interaction",
  GET_SETTINGS: "/settings",
  SESSIONS: "/sessions",
  VERSIONS: "/versions",
  ADDRESS: "/address",
  PRIVATE_ADDRESS_INFO: "/private",
  AUTH: "/auth",
  AUDIO: "/audio",
  PROCESSING_STATUS: "/status",
  TAGS: "/tags",
  TAG_CATEGORIES: "/tags/categories",
  ADMINS: "/admins",
  CREATORS: "/creators",
  CREATOR_APPLICATIONS: "/creator-applications",
  APPLICATIONS: "/applications",
  APPLICATION_TRACKS: "/applications/tracks",
  NEWSLETTER: "/newsletter",
  STEMS_CAROUSEL: "/settings/stems-carousel",
  VERSION_AUDIO_VALIDATE: "/versions/audio/validate",
};
